"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import {
  FileText,
  Download,
  Plus,
  Clock,
  CheckCircle,
  Loader2,
  RefreshCw,
  FileBarChart,
  Calendar,
  Filter,
  Brain,
  ShieldCheck,
  ChevronRight,
  Eye,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Skeleton } from "@/components/ui/skeleton";
import { ScrollArea } from "@/components/ui/scroll-area";
import { Separator } from "@/components/ui/separator";
import { usePolling } from "@/hooks/use-polling";
import { timeAgo, cn } from "@/lib/utils";
import type { Report, ReportTemplate } from "@/lib/types";
import type { Investigation } from "@/lib/types";

interface ReportsResponse {
  reports: Report[];
  templates: ReportTemplate[];
}

export default function ReportsPage() {
  const { data, loading, refresh } = usePolling<ReportsResponse>("/api/reports", 30000);
  const [tab, setTab] = useState("reports");
  const [filter, setFilter] = useState("");
  const [generating, setGenerating] = useState<string | null>(null);
  const [investigations, setInvestigations] = useState<Investigation[]>([]);

  useEffect(() => {
    fetch("/api/ai/investigations/list")
      .then((r) => r.json())
      .then((d) => setInvestigations(d.investigations || []))
      .catch(() => {});
  }, []);

  const reports = data?.reports || [];
  const templates = data?.templates || [];

  const filteredReports = reports.filter(
    (r) =>
      r.title.toLowerCase().includes(filter.toLowerCase()) ||
      r.template?.toLowerCase().includes(filter.toLowerCase())
  );

  const handleGenerate = async (templateId: string) => {
    setGenerating(templateId);
    try {
      await fetch("/api/reports", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ templateId }),
      });
      refresh();
    } catch {
      // Error handled silently
    } finally {
      setGenerating(null);
    }
  };

  const handleDownload = (reportId: string) => {
    window.open(`/api/reports/download?id=${encodeURIComponent(reportId)}`, "_blank");
  };

  if (loading && !data) {
    return (
      <div className="space-y-4">
        {[...Array(3)].map((_, i) => (
          <Skeleton key={i} className="h-24 rounded-lg" />
        ))}
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-lg font-semibold text-foreground flex items-center gap-2">
            <FileBarChart className="h-5 w-5 text-primary" />
            Reports
          </h2>
          <p className="text-sm text-muted-foreground">
            Generate, manage, and download security reports
          </p>
        </div>
        <Button variant="outline" size="sm" onClick={refresh}>
          <RefreshCw className="mr-1 h-3 w-3" /> Refresh
        </Button>
      </div>

      {/* Verifier Agent — Report Generation Banner */}
      <Card className="border-emerald-500/20 bg-emerald-500/5">
        <CardContent className="p-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-3">
              <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-emerald-500/10">
                <ShieldCheck className="h-5 w-5 text-emerald-400" />
              </div>
              <div>
                <p className="text-sm font-medium text-foreground">Verifier Agent — Auto Report Generation</p>
                <p className="text-xs text-muted-foreground">
                  Reports are auto-generated by the Verifier Agent via <code className="text-2xs font-mono bg-muted/30 px-1 rounded">report_builder.build_report()</code> after each investigation
                </p>
              </div>
            </div>
            <Link href="/ai-agents">
              <Button variant="ghost" size="sm" className="text-xs">
                <Brain className="mr-1 h-3 w-3" /> View Agent <ChevronRight className="ml-1 h-3 w-3" />
              </Button>
            </Link>
          </div>
        </CardContent>
      </Card>

      {/* Investigation-Linked Reports */}
      {investigations.length > 0 && (
        <Card>
          <CardHeader className="pb-2">
            <CardTitle className="flex items-center gap-2 text-sm">
              <FileBarChart className="h-4 w-4 text-nexus-purple" />
              Investigation Reports
            </CardTitle>
            <CardDescription>Auto-generated reports for completed investigations</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-2">
              {investigations
                .filter((inv) => inv.status === "closed" || inv.status === "in progress")
                .slice(0, 5)
                .map((inv) => (
                  <div key={inv.id} className="flex items-center justify-between rounded-md px-3 py-2 hover:bg-muted/20 transition-colors">
                    <div className="flex items-center gap-3">
                      <Badge
                        variant={inv.severity >= 4 ? "critical" : inv.severity >= 3 ? "high" : "medium"}
                        className="text-2xs"
                      >
                        S{inv.severity}
                      </Badge>
                      <span className="text-xs font-medium text-foreground">{inv.title}</span>
                    </div>
                    <div className="flex items-center gap-2">
                      <Badge variant={inv.status === "closed" ? "success" : "warning"} className="text-2xs">
                        {inv.status === "closed" ? "Report Ready" : "In Progress"}
                      </Badge>
                      <Link href={`/investigations/${inv.id}`}>
                        <Button variant="outline" size="sm" className="text-xs">
                          <Eye className="mr-1 h-3 w-3" /> View
                        </Button>
                      </Link>
                    </div>
                  </div>
                ))}
            </div>
          </CardContent>
        </Card>
      )}

      <Tabs value={tab} onValueChange={setTab}>
        <TabsList>
          <TabsTrigger value="reports">
            <FileText className="mr-1 h-3 w-3" /> Reports
          </TabsTrigger>
          <TabsTrigger value="templates">
            <Plus className="mr-1 h-3 w-3" /> Templates
          </TabsTrigger>
        </TabsList>

        <TabsContent value="reports" className="mt-4 space-y-4">
          <div className="flex items-center gap-2">
            <div className="relative flex-1 max-w-sm">
              <Filter className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" />
              <Input
                value={filter}
                onChange={(e) => setFilter(e.target.value)}
                placeholder="Filter reports..."
                className="pl-8 h-9 text-sm"
              />
            </div>
            <Badge variant="outline" className="text-xs">
              {filteredReports.length} reports
            </Badge>
          </div>

          <ScrollArea className="h-[500px]">
            <div className="space-y-2">
              {filteredReports.map((report) => (
                <Card key={report.id} className="hover:border-primary/30 transition-colors">
                  <CardContent className="p-4">
                    <div className="flex items-start justify-between">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <h3 className="text-sm font-medium text-foreground truncate">
                            {report.title}
                          </h3>
                          <Badge
                            variant={
                              report.status === "completed"
                                ? "success"
                                : report.status === "generating"
                                  ? "warning"
                                  : "ghost"
                            }
                            className="text-2xs shrink-0"
                          >
                            {report.status === "generating" && (
                              <Loader2 className="mr-1 h-2.5 w-2.5 animate-spin" />
                            )}
                            {report.status}
                          </Badge>
                        </div>
                        <div className="mt-1 flex items-center gap-3 text-2xs text-muted-foreground">
                          {report.template && <span>{report.template}</span>}
                          <span>·</span>
                          <span className="flex items-center gap-1">
                            <Clock className="h-2.5 w-2.5" />
                            {timeAgo(report.created)}
                          </span>
                          {report.pages && (
                            <>
                              <span>·</span>
                              <Badge variant="outline" className="text-2xs">
                                {report.pages} pages
                              </Badge>
                            </>
                          )}
                        </div>
                      </div>
                      {report.status === "completed" && (
                        <Button
                          variant="outline"
                          size="sm"
                          onClick={() => handleDownload(report.id)}
                          className="shrink-0 text-xs"
                        >
                          <Download className="mr-1 h-3 w-3" /> Download
                        </Button>
                      )}
                    </div>
                  </CardContent>
                </Card>
              ))}

              {filteredReports.length === 0 && (
                <div className="py-12 text-center text-sm text-muted-foreground">
                  {filter ? "No reports match your filter" : "No reports generated yet"}
                </div>
              )}
            </div>
          </ScrollArea>
        </TabsContent>

        <TabsContent value="templates" className="mt-4 space-y-4">
          <div className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3">
            {templates.map((tpl) => (
              <Card key={tpl.id}>
                <CardContent className="p-4 space-y-3">
                  <div>
                    <h3 className="text-sm font-medium text-foreground">{tpl.name}</h3>
                    <p className="mt-0.5 text-xs text-muted-foreground">{tpl.description}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    {tpl.icon && (
                      <Badge variant="ghost" className="text-2xs">
                        {tpl.icon}
                      </Badge>
                    )}
                  </div>
                  <Button
                    variant="cyan"
                    size="sm"
                    className="w-full text-xs"
                    onClick={() => handleGenerate(tpl.id)}
                    disabled={generating === tpl.id}
                  >
                    {generating === tpl.id ? (
                      <Loader2 className="mr-1 h-3 w-3 animate-spin" />
                    ) : (
                      <Plus className="mr-1 h-3 w-3" />
                    )}
                    Generate Report
                  </Button>
                </CardContent>
              </Card>
            ))}

            {templates.length === 0 && (
              <div className="col-span-full py-12 text-center text-sm text-muted-foreground">
                No report templates available
              </div>
            )}
          </div>
        </TabsContent>
      </Tabs>
    </div>
  );
}
